esphome:
  name: bm2
  
  includes:
    - include.h

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

logger:
  level: INFO

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

mqtt:
  broker: !secret mqtt_hostname
  discovery: false
  topic_prefix: esphome/bm2

web_server:
  port: 80

<<: !include bm2.yaml
